# Generated by Django 6.0.6 on 2026-07-03 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='website',
        ),
        migrations.AddField(
            model_name='company',
            name='currency',
            field=models.CharField(default='UGX', max_length=10),
        ),
    ]
