# Generated by Django 6.0.6 on 2026-07-03 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_remove_company_website_company_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='currency',
            field=models.CharField(choices=[('UGX', 'Ugandan Shilling'), ('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('KES', 'Kenyan Shilling'), ('TZS', 'Tanzanian Shilling')], default='UGX', max_length=10),
        ),
    ]
